CREATE TABLE USER (
	ID LONG AUTO_INCREMENT, 
	USERNAME VARCHAR(50) NOT NULL, 
	PASSWORD VARCHAR(100) NOT NULL, 
	CONSTRAINT pk_USER PRIMARY KEY (ID)
);

CREATE INDEX IDX_USERNAME_USER ON USER (USERNAME);

CREATE TABLE AUTHORITY (
	ID LONG AUTO_INCREMENT, 
	NAME VARCHAR(50) NOT NULL,
	CONSTRAINT pk_AUTHORITY PRIMARY KEY (ID)
);

CREATE TABLE USER_AUTHORITY (
	USER_ID LONG NOT NULL, 
	AUTHORITY_ID LONG NOT NULL
);

CREATE INDEX IDX_USER_AUTHORITY_ID ON USER_AUTHORITY (USER_ID, AUTHORITY_ID);

CREATE TABLE LOCATION_POINT (
	ID LONG AUTO_INCREMENT, 
	NAME VARCHAR(100) NOT NULL, 
	ADDRESS VARCHAR(200) NOT NULL, 
	PROVINCE VARCHAR(50) NOT NULL, 
	CITY VARCHAR(50) NOT NULL, 
	AREA VARCHAR(50) NOT NULL, 
	STREET_ID VARCHAR(100) NOT NULL, 
	LOGIN_ID VARCHAR(100) NOT NULL, 
	DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	CONSTRAINT pk_LOCATION_POINT PRIMARY KEY (ID)
);

CREATE INDEX IDX_NAME_LOCATION_POINT ON LOCATION_POINT (NAME);